### ISSUE TITLE
No request(empty array) returned from intercept service

### ISSUE THREAD

**Issue by sindhubee** [webdriverio-community/wdio-intercept-service#505]
Using WebdriverIO version **8.3.5**  and wdio-intercept-service version **4.3.1** 

Below snippet is the test i'm running :

```
 it('should open page', async () => {
  await browser.url(`http://localhost:8080/`)
  await browser.setupInterceptor();
  await browser.refresh();
  await playerControls.clickBigPlayButton();
  await testHelper.delay(5000);
  var request = await browser.getRequest({includingPending:true})
  console.log("Printing request");
  console.log(request);
  })
```

Here is the output(with empty array)
`[0-0] 2023-02-23T18:31:22.827Z INFO webdriver: DATA { script: 'getRequest(...) [2021 bytes]', args: [ undefined, {} ] }
[0-0] 2023-02-23T18:31:22.835Z INFO webdriver: RESULT []
[0-0] 2023-02-23T18:31:22.841Z INFO webdriver: RESULT []
[0-0] Printing request
[0-0] []`

Here is my capabilities in wdio.conf.js

```
  capabilities: [{

    maxInstances: 5,
    /
    browserName: 'chrome',
    'goog:perfLoggingPrefs': {
      enableNetwork: true
  },
     acceptInsecureCerts: true

  }],
```

Im running the app but pointing to localhost. Could this be an issue? If yes, are there any workarounds that you could suggest.

I have made sure I am running same chrome driver version as the browser on local machine , Please help with anything I might be missing . TIA .

**Comment by tehhowch** [comment]
The problem there is likely that you refreshed the page after you set up the interceptor.

**Comment by sindhubee** [comment]
Tried to remove the refresh and I still get the same empty array.

**Comment by tehhowch** [comment]
If the code you've provided above is what is in your spec file, then this line is also to blame:

```js
var request = await browser.getRequest({includingPending:true})
```

per the [API for `getRequest`](https://github.com/webdriverio-community/wdio-intercept-service#browsergetrequestindex-number--includepending-boolean-orderby-start--end---), that should be `getRequest(0, { includePending: true});`

or you can use `getRequests({ includePending: true });` if you want to receive all requests that have been logged so far and find the match in the nodejs process.


As for what is happening with the code you are using, you are passing `{includePending: true}` as the `index` property, which compares `false` here:
https://github.com/webdriverio-community/wdio-intercept-service/blob/273ac93fce5fe9482165d3fc30bc3e0c21b224fc/index.js#L283
and thus we enter this branch, returning all completed requests to the nodejs process
https://github.com/webdriverio-community/wdio-intercept-service/blob/273ac93fce5fe9482165d3fc30bc3e0c21b224fc/lib/interceptor.js#L393-L394
and then since the return value is an array, this logic runs:
https://github.com/webdriverio-community/wdio-intercept-service/blob/273ac93fce5fe9482165d3fc30bc3e0c21b224fc/index.js#L294-L295

A PR that throws a `TypeError` for invalid `index` parameters would help catch this sooner, contributions are welcome.

**Comment by sindhubee** [comment]
Adding more context - When i try to intercept a public page like "https://google.com" i'm seeing traffic, which for me seems like it is an issue intercepting localhost. I also tried the following with no luck : 

- Changed localhost:8080 to localhost.:8080
- Used ip address http://127.0.0.1:8080

**Comment by tehhowch** [comment]
> Hi @tehhowch Thank you for your inputs. I tried using `getRequests({ includePending: true });` but I'm still not getting any traffic.
> 
> Adding a note here - Im running the app but pointing to localhost. Could this be an issue? If yes, are there any workarounds that you could suggest.

localhost is not an issue; this service's tests intercept traffic on localhost. Please verify the versions of WebdriverIO and of this service that you are using, as you have not provided that critical information.

**Comment by sindhubee** [comment]
Hi @tehhowch I'm using WebdriverIO version **8.3.5**  and wdio-intercept-service version **4.3.1**

**Comment by sindhubee** [comment]
Also at times i keep getting this error 

`[0-0] 2023-02-27T04:04:54.648Z WARN webdriver: Request failed with status 500 due to javascript error: Failed to read the 'sessionStorage' property from 'Window': Storage is disabled inside 'data:' URLs.
[0-0] JavaScript stack:
[0-0] Error: Failed to read the 'sessionStorage' property from 'Window': Storage is disabled inside 'data:' URLs.
[0-0]     at supportsSessionStorage (eval at executeAsyncScript (:552:26), <anonymous>:255:23)
[0-0]     at setup (eval at executeAsyncScript (:552:26), <anonymous>:18:9)
[0-0]     at eval (eval at executeAsyncScript (:552:26), <anonymous>:324:6)
[0-0]     at eval (eval at executeAsyncScript (:552:26), <anonymous>:325:4)
[0-0]     at executeAsyncScript (<anonymous>:552:47)
[0-0]     at <anonymous>:567:29
[0-0]     at callFunction (<anonymous>:446:22)
[0-0]     at <anonymous>:460:23
[0-0]     at <anonymous>:461:3
[0-0]   (Session info: chrome=110.0.5481.177)`

**Comment by sindhubee** [comment]
@tehhowch  Any update on this please?

**Comment by sindhubee** [comment]
Turns out the network requests that i'm trying to intercept are not fetch/xhr type and hence i'm receiving an empty list. Closing this issue.
