### ISSUE TITLE
Getting [wdio-intercept-service]: the "index" property must be a non-negative integer error while trying to capture GET request

### ISSUE THREAD

**Issue by vinaybalepur** [webdriverio-community/wdio-intercept-service#710]
Hi. I am new to webdriverio and when trying to capture network calls using following code, I am getting "[wdio-intercept-service]: the "index" property must be a non-negative integer" error. In the network console I am able to see the request and respone.

var req = await browser.getRequest('GET', "https://completion.amazon.in/api/2017/suggestions")
console.log(req)

Complete error
TypeError: [wdio-intercept-service]: the "index" property must be a non-negative integer
at Browser.getRequest (/Users/vinayb/Documents/webdriverio/node_modules/wdio-intercept-service/index.js:283:15)

**Comment by tehhowch** [comment]
I'm not sure what your question is -- the signature for the `getRequest` function is shown in [the README: ](https://github.com/webdriverio-community/wdio-intercept-service#browsergetrequestindex-number--includepending-boolean-orderby-start--end---)

What you show looks more like an attempt to use `browser.expectRequest`, rather than `browser.getRequest`
